port: 8080
public_dir: "public"
listen:
    - 127.0.0.1
google_analytics_id: ""
tls:
    caChainFile: "server.crt"
    privateKeyFile: "server.pem"
    port: 8443
exec:
    driver: "stupidlocal"
    # driver: "off"
    # driver: "docker"
    # # For docker driver
    # config:
    #     memory_limit: 128
    #     maximum_queue_size: 10
    #     time_limit: 10
    #     maximum_output_size: 4096
    cache: true
